# Generated by Django 5.2.7 on 2025-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publications_status",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
